[package]
name = "rhythmical"
version = "0.1.0"
authors = ["Robert Brignull <robertbrignull@gmail.com>"]
build = "build.rs"

[dependencies]
rocket = "0.3.17"
rocket_contrib = "0.3.17"
rocket_codegen = "0.3.17"
serde_derive = "1.0.80"
serde_json = "1.0.32"
serde = "1.0.80"
lazy_static = "1.1.0"
percent-encoding = "1.0.1"
htmlescape = "0.3.1"
