[package]
name = "rhythmical"
version = "0.1.0"
authors = ["Robert Brignull <robertbrignull@gmail.com>"]
build = "build.rs"

[dependencies]
rouille = "3.0.0"
serde_derive = "1.0.87"
serde_json = "1.0.38"
serde = "1.0.87"
lazy_static = "1.2.0"
percent-encoding = "1.0.1"
htmlescape = "0.3.1"
regex = "1.1.0"
